### ISSUE TITLE
안녕하세요 AWS Cognito 관련 질문합니다

### ISSUE THREAD

**Issue by idealist33** [pyrasis/awsbook#2]
안녕하세요 책 구입해서 잘 보고 있는데요 아쉽게도 Cognito는 출간 전에 완료하셨다고 하셔서 기재되어있지는 않네요 
크게 보면 페이스북 로그인은 sdk가 있어서 유니티에서 잘 적용했는데요
Kakao로그인 같은 경우는 어떻게 Cognito와 연동할지 감이 잘 안 서네요
게임에 페이스북과 카카오로그인을 동시에 사용하려고 하는데 Kakao는 Cognito를 공식 지원하지 않네요
이런 경우는 어떻게 해야할지요..Kakao로그인은 Rest API로 구현했습니다..

**Comment by pyrasis** [comment]
제가 cognito를 좀 살펴봤는데요. 구현 가능 여부를 판단하기에는 시간이 다소 걸릴 듯 합니다.

AWS 한국지사에 기술지원을 요청하시는 것을 권해드립니다. 

기술지원은 개발자 서포트 플랜으로 요청하시면 됩니다. 

https://aws.amazon.com/ko/premiumsupport/developer-support/
